# site settings
title: Sunil Patel
subtitle: Deep Learning Data Scientist -IV, Nvidia
email: snlpatel001213@hotmail.com
description: This is my profile page to show what my regular resume cannot...<br/> This is the place to present what I did in my career.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://snlpatel001213.github.io/" # the base hostname & protocol for your site
author: Sunil Patel
street_address: B-602, Lakeshoregreen,
city: Mumbai
state: MH
zip_code: 55555
country: India
phone: (886) 633-6960

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/snlpatel001213
  # GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  # Instagram:
  LinkedIn: https://www.linkedin.com/in/linus1
  # Twitter: https://twitter.com/andrewbanchich
  # Facebook:
  # Slack:

# build settings
markdown: kramdown
usemathjax: true


sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
